-- ================================================
-- Migration 023: Cleanup Old Policy Names
-- ================================================
-- Created: 2026-01-21
-- Description: Remove old policy naming convention that still triggers lint warnings
-- ================================================
-- ISSUE: Supabase lint 0012 still reports warnings because old policies
--        with names like "orders_admin_*" still exist alongside new policies.
--        Storage policies also have duplicates with auto-generated suffixes.
-- ================================================
-- SOLUTION: Drop all old policy names that don't have explicit is_anonymous check
-- ================================================

-- ================================================
-- PART 1: orders - Drop old naming convention
-- ================================================

DROP POLICY IF EXISTS "orders_admin_select" ON orders;
DROP POLICY IF EXISTS "orders_admin_update" ON orders;
DROP POLICY IF EXISTS "orders_admin_delete" ON orders;
DROP POLICY IF EXISTS "orders_admin_insert" ON orders;

-- ================================================
-- PART 2: order_items - Drop old naming convention
-- ================================================

DROP POLICY IF EXISTS "order_items_admin_select" ON order_items;
DROP POLICY IF EXISTS "order_items_admin_update" ON order_items;
DROP POLICY IF EXISTS "order_items_admin_delete" ON order_items;
DROP POLICY IF EXISTS "order_items_admin_insert" ON order_items;

-- ================================================
-- PART 3: storage.objects - Drop duplicate policies with auto-generated suffixes
-- ================================================
-- These were created by Supabase Dashboard when policies with same name existed
-- The suffixes like "bjsgsj_0", "1e6ovep_0", "vbjyiy_0" are auto-generated

DO $$
DECLARE
  policy_record RECORD;
  drop_count INTEGER := 0;
BEGIN
  -- STEP 1: Explicitly drop known duplicate policies (from lint report)
  -- These have space + random suffix format generated by Supabase
  DROP POLICY IF EXISTS "blog_images_admin_delete bjsgsj_0" ON storage.objects;
  DROP POLICY IF EXISTS "blog_images_admin_update bjsgsj_0" ON storage.objects;
  DROP POLICY IF EXISTS "products_images_admin_delete 1e6ovep_0" ON storage.objects;
  DROP POLICY IF EXISTS "products_images_admin_update 1e6ovep_0" ON storage.objects;
  DROP POLICY IF EXISTS "products_pdfs_admin_delete vbjyiy_0" ON storage.objects;
  DROP POLICY IF EXISTS "products_pdfs_admin_select vbjyiy_0" ON storage.objects;
  DROP POLICY IF EXISTS "products_pdfs_admin_update vbjyiy_0" ON storage.objects;

  RAISE NOTICE '✅ Dropped explicitly named duplicate storage policies';

  -- STEP 2: Find and drop any remaining policies with auto-generated suffixes
  -- Pattern: policy name ends with space + alphanumeric + underscore + number
  FOR policy_record IN
    SELECT policyname
    FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname ~ ' [a-z0-9]+_[0-9]+$'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON storage.objects', policy_record.policyname);
    drop_count := drop_count + 1;
    RAISE NOTICE 'Dropped additional duplicate storage policy: %', policy_record.policyname;
  END LOOP;

  IF drop_count > 0 THEN
    RAISE NOTICE '✅ Dropped % additional duplicate storage policies via regex', drop_count;
  END IF;
EXCEPTION
  WHEN insufficient_privilege THEN
    RAISE WARNING '⚠️  Cannot drop storage policies (insufficient privileges)';
    RAISE WARNING '    Please delete manually via Supabase Dashboard → Storage → Policies';
END $$;

-- ================================================
-- SUCCESS MESSAGE
-- ================================================
DO $$
BEGIN
  RAISE NOTICE '';
  RAISE NOTICE '================================================';
  RAISE NOTICE '✅ Migration 023 completed!';
  RAISE NOTICE '================================================';
  RAISE NOTICE '';
  RAISE NOTICE '🧹 CLEANUP PERFORMED:';
  RAISE NOTICE '   ✅ Dropped old orders_admin_* policies';
  RAISE NOTICE '   ✅ Dropped old order_items_admin_* policies';
  RAISE NOTICE '   ✅ Dropped duplicate storage policies with auto-generated suffixes';
  RAISE NOTICE '';
  RAISE NOTICE '🎯 RESULT:';
  RAISE NOTICE '   Lint warning 0012 should now be fully resolved.';
  RAISE NOTICE '   Only policies with explicit is_anonymous check remain.';
  RAISE NOTICE '';
END $$;
